apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backplane-acs-rhacs-secured-cluster
  namespace: rhacs-secured-cluster
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    resourceNames:
      - admission-control-tls
      - collector-tls
      - sensor-tls
    verbs:
      - create
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
    resourceNames:
      - sensor
      - collector
      - admission-control
    verbs:
      - get
      - patch
